ARG BASE_IMAGE
ARG BASE_IMAGE_VERSION

FROM op-01.gzproduction.com/kd-recog/$BASE_IMAGE:$BASE_IMAGE_VERSION

ARG JENKINS_PROJECT_FOLDER_NAME
LABEL MAINTAINER='xumaozhou@kuandeng.com'

USER root

# 安装系统依赖库（新增librdkafka）
RUN apt-get update && \
    apt-get install -y \
    libboost-filesystem-dev \
    librdkafka-dev \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 合并Python包安装（新增tos）
RUN pip install \
    tos \
    utm \
    gputil \
    oss2 \
    confluent-kafka==1.9.2 \
    elasticsearch==7.13.4 \
    minio

# USER hadoop

# add execute file into docker
RUN mkdir -p /home/hadoop/bin/
# COPY --chown=hadoop:hadoop $JENKINS_PROJECT_FOLDER_NAME/ /home/hadoop/bin/
COPY $JENKINS_PROJECT_FOLDER_NAME/* /home/hadoop/bin/
WORKDIR /home/hadoop/bin/